title: "Saravana Hari M Portfolio"
author: "Saravana Hari M"
description: "AI/ML Enthusiast | Civil Engineer | Tech Explorer"
theme: minima
baseurl: "" 
url: "https://your-github-username.github.io"
